[workspace.package]
edition = "2021"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
homepage = "https://github.com/agerasev/ringbuf"
repository = "https://github.com/agerasev/ringbuf.git"
readme = "README.md"
license = "MIT/Apache-2.0"

[workspace.dependencies]
ringbuf = { path = ".", version = "0.3.3" }

[workspace]
members = ["blocking"]

[package]
name = "ringbuf"
version = "0.3.3"
edition.workspace = true
authors.workspace = true
description = "Lock-free SPSC FIFO ring buffer with direct access to inner data"
documentation = "https://docs.rs/ringbuf"
repository.workspace = true
keywords = ["lock-free", "spsc", "ring-buffer", "rb", "fifo"]
categories = ["concurrency", "data-structures", "no-std"]
license.workspace = true

[features]
default = ["alloc", "std"]
alloc = []
std = ["alloc"]
bench = []

[dependencies]
crossbeam-utils = { version = "0.8", default-features = false }

[[example]]
name = "simple"
required-features = ["alloc"]

[[example]]
name = "overwrite"
required-features = ["alloc"]

[[example]]
name = "message"
required-features = ["std"]
